export enum ClasificacionCuenta {
  // Activo
  ACTIVO_CIRCULANTE = 'ACTIVO_CIRCULANTE',
  ACTIVO_FIJO = 'ACTIVO_FIJO',
  ACTIVO_DIFERIDO = 'ACTIVO_DIFERIDO',

  // Pasivo
  PASIVO_CORTO_PLAZO = 'PASIVO_CORTO_PLAZO',
  PASIVO_LARGO_PLAZO = 'PASIVO_LARGO_PLAZO',
  PASIVO_DIFERIDO = 'PASIVO_DIFERIDO',

  // Otros
  CAPITAL = 'CAPITAL',
  INGRESOS = 'INGRESOS',
  COSTOS = 'COSTOS',
  GASTOS = 'GASTOS',
}